# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target 'Rikkeify' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Rikkeify
  
  # d.i
  pod 'Swinject'
  
  post_install do |pi|
        pi.pods_project.targets.each do |target|
            target.build_configurations.each do |config|
                config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
            end
        end
    end
end
